---
# tasks file for update
- name:
  apt:
    name:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - gpg
      - sudo
      - wget
    update_cache: yes






