---
- name: install haproy
  hosts: ha_prox
  become: yes
  roles:
    - haproxy 
    - keepalived 
- name: install k8s
  hosts: hosts
  become: yes
  roles:
    - programs
    - ntp
    - swap_off
    - mod_forwd
    - k8s_repo
    - kub_kubeadm_kubctl
    - cri-o
- name: control plane
  hosts: master
  become: yes
  roles:
    - control
    - calico
    - helm
    - helm_install

- name: control plane
  hosts: control
  become: yes
  roles:
    - init_control
- name: workers
  hosts: worker
  become: yes
  roles:
    - init_worker

...

