---

   - debug:
       var: join_command
   
   - debug:
       var: control_plane_certkey


   - name: join control-plane nodes
     shell: "{{join_command}} --control-plane --certificate-key {{control_plane_certkey}}"
     args:
       chdir: $HOME
       creates: node_joined.txt
   - name: create .kube directory
     file:
       path: $HOME/.kube
       state: directory
       mode: 0755

   - name: copy admin.conf to user's kube config
     copy:
       src: /etc/kubernetes/admin.conf
       dest: $HOME/.kube/config
       remote_src: yes

